name: unit-lint-typecheck-e2e-ct
on:
  push:
  workflow_dispatch:

env:
  VITE_PORT: 3000
  API_PORT: 3001
  VITE_API_URL: 'http://localhost:3001'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # if you want to enable parallelization
  # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Install NPM dependencies, cache node-modules and Cypress correctly
      # https://github.com/cypress-io/github-action
      - name: Install dependencies
        uses: cypress-io/github-action@v6.7.7
        with:
          runTests: false

  unit-test:
    needs: [install-dependencies]
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        uses: cypress-io/github-action@v6.7.7
        with:
          runTests: false
      - name: unit-test
        run: npm run test:coverage

  lint:
    needs: install-dependencies
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        uses: cypress-io/github-action@v6.7.7
        with:
          runTests: false
      - name: lint
        run: npm run lint

  typecheck:
    needs: install-dependencies
    name: Run typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        uses: cypress-io/github-action@v6.7.7
        with:
          runTests: false
      - name: typecheck
        run: npm run typecheck

  cypress-e2e-test:
    # if you want to enable parallelization
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     machines: [1, 2]
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    # container: cypress/included:10.11.0 #  no need when using cypress gha to install dependencies
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cypress e2e tests 🧪
        uses: cypress-io/github-action@v6.7.7
        with:
          # install: false # Cypress gha will take care of install instead of bahmutov/installs
          start: npm run start
          wait-on: 'http://localhost:3000'
          browser: chrome
          config-file: cypress/config/local.config.ts
          # if you want to enable parallelization
          # record: true
          # parallel: true
          # group: e2e-tests
          # tag: e2e-tests

  cypress-ct-test:
    # if you want to enable parallelization
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     machines: [1, 2, 3]
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    # container: cypress/included:10.11.0 # no need when using cypress gha to install dependencies
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cypress component tests 🧪
        uses: cypress-io/github-action@v6.7.7
        with:
          # we have already installed everything
          # install: false # Cypress gha will take care of caching instead of bahmutov/installs
          component: true
          browser: chrome
          config-file: cypress/config/local.config.ts
          # if you want to enable parallelization
          # record: true
          # parallel: true
          # group: ct-tests
          # tag: ct-tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
